[package]
name = "rocksdb-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.44"
rocksdb = { git = "https://github.com/Rexagon/rust-rocksdb.git", features = ["jemalloc", "multi-threaded-cf"] }
