[package]
name = "rocksdb-builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocksdb = { git = "https://github.com/broxus/rust-rocksdb.git", features = ["jemalloc", "multi-threaded-cf"] }
anyhow = "1.0.44"